### PR TITLE
XIVY-12288 integration test

### PR DESCRIPTION
**Pull request by ivy-lgi**
- integration test to load and display data of data class, business data class and entity class
- mock test to assert detail content when a field is selected or not

### CODE REVIEW

**Comment by ivy-lgi** [comment]
@ivy-lli any idea why the integration test is failing on chromium? It's only showing a white page and it works on my machine.

**Comment by ivy-lli** [comment]
Please have a look on the form editor integration test setup, to learn how to create the correct engine test environment :)

**Comment by ivy-lgi** [comment]
Was just missing in the `feature.xml`. Works now. Please review :smile:

**Review by ivy-lli — APPROVED** [review]
As soon as you add edit integration tests you will need to have a look at the form editor integration setup, but yes looks fine 👍

**Review by ivy-lli — APPROVED** [review]
thx 👍

**Pull request merged**
