### PR TITLE
XIVY-15138 automatically create types from schema :scroll: :page_facing_up: 

### PR DESCRIPTION
**Pull request by ivy-rew**

### CODE REVIEW

**Review by ivy-edp — APPROVED** [review]
Nice 👍

**Comment by ivy-edp** [comment]
@ivy-lgi Perhaps the code owner could also take a look.

**Comment by ivy-lgi** [comment]
Took a quick look. Very cool, thanks :+1: 
This is still missing from the Variables Editor, in case someone is bored :eyes:

**Comment by ivy-edp** [comment]
I think the problem that some IT are not running is that in the file DataClassMasterContent the DataClassField import is wrong. It is currently like this:
`import { type DataClassField } from '@axonivy/dataclass-editor-protocol';`
As far as I know, it should be like this:
`import type { DataClassField } from '@axonivy/dataclass-editor-protocol';`

**Comment by ivy-rew** [comment]
> Took a quick look. Very cool, thanks 👍 This is still missing from the Variables Editor, in case someone is bored 👀

Gonna check this in this sprint if possible  or create a story for this

**Pull request merged**
